

// 书影音-电影
export const MOVIE_HOME_REQUEST = "MOVIE_HOME_REQUEST";
export const MOVIE_HOME_RECEIVE_SUCCESS = "MOVIE_HOME_RECEIVE_SUCCESS";
export const MOVIE_HOME_RECEIVE_FAILED = "MOVIE_HOME_RECEIVE_FAILED";

export const MOVIE_TOP250_REQUEST = "MOVIE_TOP250_REQUEST";
export const MOVIE_TOP250_RECEIVE_SUCCESS = "MOVIE_TOP250_RECEIVE_SUCCESS";
export const MOVIE_TOP250_RECEIVE_FAILED = "MOVIE_TOP250_RECEIVE_FAILED";
//
// export const MOVIE_NICE_WEEKLY_REQUEST = "MOVIE_NICE_WEEKLY_REQUEST";
// export const MOVIE_NICE_RECEIVE_SUCCESS = "MOVIE_NICE_RECEIVE_SUCCESS";
// export const MOVIE_NICE_RECEIVE_FAILED = "MOVIE_NICE_RECEIVE_FAILED";
//
// export const MOVIE_NEW_REQUEST = "MOVIE_NEW_REQUEST";
// export const MOVIE_NEW_RECEIVE_SUCCESS = "MOVIE_NEW_RECEIVE_SUCCESS";
// export const MOVIE_NEW_RECEIVE_FAILED = "MOVIE_NEW_RECEIVE_FAILED";

// 书影音-读书

// 书影音-音乐


/**
 * Tab 搜索
 */

export const SEARCH_INDEX_REQUEST = 'SEARCH_INDEX_REQUEST';
export const SEARCH_INDEX_RECEIVE_SUCCESS = 'SEARCH_INDEX_RECEIVE_SUCCESS';
export const SEARCH_INDEX_RECEIVE_FAILED='SEARCH_INDEX_RECEIVE_FAILED';

export const BOOK_SEARCH_REQUEST = 'BOOK_SEARCH_REQUEST';
export const BOOK_SEARCH_RECEIVE_SUCCESS='BOOK_SEARCH_RECEIVE_SUCCESS';
export const BOOK_SEARCH_RECEIVE_FAILED='BOOK_SEARCH_RECEIVE_FAILED';

export const MOVIE_SEARCH_REQUEST = 'MOVIE_SEARCH_REQUEST';
export const MOVIE_SEARCH_RECEIVE_SUCCESS='MOVIE_SEARCH_RECEIVE_SUCCESS';
export const MOVIE_SEARCH_RECEIVE_FAILED='MOVIE_SEARCH_RECEIVE_FAILED';

export const MUSIC_SEARCH_REQUEST = 'MUSIC_SEARCH_REQUEST';
export const MUSIC_SEARCH_RECEIVE_SUCCESS='MUSIC_SEARCH_RECEIVE_SUCCESS';
export const MUSIC_SEARCH_RECEIVE_FAILED = 'MUSIC_SEARCH_RECEIVE_FAILED';